example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.datasource.driver-class-name: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://manny.db.elephantsql.com:5432/yumiazwy"
spring.datasource.username: "yumiazwy"
spring.datasource.password: "vUU2GGpQgIq4pfLbHwq9SyfKlAI-mCQD"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"