example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://scvsbtjjszlyvq:e175cf38c2d8c7ba71f0c132aaa8d39ac4da71a9ed1868e66f0a78d157ebb324@ec2-54-163-246-159.compute-1.amazonaws.com:5432/d53hrkvjo19loc"
spring.datasource.username: "scvsbtjjszlyvq"
spring.datasource.password: "e175cf38c2d8c7ba71f0c132aaa8d39ac4da71a9ed1868e66f0a78d157ebb324"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"